version: '3'

services:

  consulta:
    build: './consulta'
    ports:
      - 80:80
    depends_on:
      - rabbit
      - mongo

  # financeiro:
  #   build: './financeiro'
  #   depends_on:
  #     - rabbit
  #     - mongo

  rabbit:
    hostname: rabbit
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

  mongo:
    restart: always
    image: 'mongo'
    ports:
      - '27017:27017'



